#!/usr/bin/env bash
# ===================================================================
# Gold Scalper -- Render Build Script
# Generated by _render_optimize.py
#
# Render free tier: 512 MB RAM, shared CPU
# This script trains Brain models on first deploy if not present.
# ===================================================================
set -euo pipefail

echo "=============================================="
echo "  Gold Scalper -- Render Build"
echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "=============================================="

# -- Step 1: Install dependencies --
echo ""
echo "-> Step 1/5: Installing dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

# -- Step 2: Create required directories --
echo ""
echo "-> Step 2/5: Creating directories..."
mkdir -p models/brain
mkdir -p data/brain_decisions
mkdir -p data

# -- Step 3: Train Brain models if not present --
echo ""
echo "-> Step 3/5: Checking Brain models..."
BRAIN_DIR="models/brain"
REQUIRED_MODELS=(
    "thesis_validator.onnx"
    "meta_fusion_xgb.onnx"
    "meta_fusion_lgb.onnx"
    "meta_fusion_nn.onnx"
    "meta_fusion_rf.onnx"
    "twin_calibrator.onnx"
)

NEED_TRAIN=false
for model in "${REQUIRED_MODELS[@]}"; do
    if [ ! -f "$BRAIN_DIR/$model" ]; then
        # Check joblib fallback
        JB_MODEL="${model%.onnx}.joblib"
        if [ ! -f "$BRAIN_DIR/$JB_MODEL" ]; then
            echo "  Missing: $model (and no joblib fallback)"
            NEED_TRAIN=true
        fi
    fi
done

if [ "$NEED_TRAIN" = true ]; then
    echo ""
    echo "  Training Brain models (this may take 2-5 minutes)..."
    python _train_brain.py --output "$BRAIN_DIR" --samples 15000
    echo "  Brain training complete."
else
    echo "  All Brain models present -- skipping training."
fi

# -- Step 4: Verify all ONNX models --
echo ""
echo "-> Step 4/5: Verifying models..."
python -c "
import sys, os
brain_dir = '$BRAIN_DIR'
required = ['thesis_validator', 'meta_fusion_xgb', 'meta_fusion_lgb',
             'meta_fusion_nn', 'meta_fusion_rf',
             'twin_calibrator']
ok = 0
fail = 0
for name in required:
    onnx = os.path.join(brain_dir, f'{name}.onnx')
    jb = os.path.join(brain_dir, f'{name}.joblib')
    if os.path.exists(onnx):
        try:
            import onnxruntime as ort
            ort.InferenceSession(onnx)
            print(f'  OK   {name}.onnx')
            ok += 1
        except Exception as e:
            print(f'  ERR  {name}.onnx -- {e}')
            fail += 1
    elif os.path.exists(jb):
        print(f'  OK   {name}.joblib (fallback)')
        ok += 1
    else:
        print(f'  MISS {name} -- not found')
        fail += 1
print(f'')
print(f'  Models: {ok} OK, {fail} missing/failed')
if fail > 0:
    sys.exit(1)
"

# -- Step 5: Set permissions --
echo ""
echo "-> Step 5/5: Setting permissions..."
chmod -R 755 models/ 2>/dev/null || true
chmod -R 755 data/ 2>/dev/null || true

echo ""
echo "=============================================="
echo "  Build complete!"
echo "=============================================="
