$env:JAVA_HOME = "C:\jdk17\jdk-17.0.2"
$env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
Set-Location "C:\Users\Sir AK HEE\Desktop\MY PROJECTS\QuantoraFX (scalping machine)\gold_scalper_app"
& "C:\flutter\bin\flutter.bat" build apk --release --android-skip-build-dependency-validation 2>&1 | Tee-Object -FilePath "build_output.txt"
Write-Host "`n=== BUILD DONE ==="
